export interface EventConfig {
  name: string;
  description?: string;
}

export interface PropConfig {
  name: string;
  type: 'string' | 'number' | 'boolean' | 'select' | 'json';
  options?: string[]; // For select type
  defaultValue?: any;
  label?: string; // Short label for controls
  description?: string; // Detailed description for docs
}

export interface ComponentConfig {
  id: string; // Nav ID
  tagName: string;
  label: string;
  description?: string;
  features?: string[];
  props: PropConfig[];
  slots?: { name: string; content: string }[]; // Default slot content
  events?: EventConfig[];
  allowTrigger?: boolean;
  triggerLabel?: string;
}

export const COMPONENT_CONFIGS: Record<string, ComponentConfig> = {
  button: {
    id: 'button',
    tagName: 'ui-button',
    label: 'Button',
    description:
      'A versatile button component with multiple variants, sizes, and advanced layout options.',
    props: [
      { name: 'label', type: 'string', defaultValue: 'Click Me' },
      {
        name: 'variant',
        type: 'select',
        options: [
          'primary',
          'secondary',
          'success',
          'danger',
          'warning',
          'info',
          'outline',
          'ghost',
        ],
        defaultValue: 'primary',
      },
      {
        name: 'size',
        type: 'select',
        options: ['xs', 'sm', 'md', 'lg', 'xl'],
        defaultValue: 'md',
      },
      { name: 'icon', type: 'string', defaultValue: '' },
      {
        name: 'iconPosition',
        type: 'select',
        options: ['left', 'right', 'top', 'bottom'],
        defaultValue: 'left',
      },
      { name: 'iconOnly', type: 'boolean', defaultValue: false },
      { name: 'badge', type: 'string', defaultValue: '' },
      { name: 'loading', type: 'boolean', defaultValue: false },
      {
        name: 'loadingPosition',
        type: 'select',
        options: ['left', 'right', 'top', 'bottom'],
        defaultValue: 'left',
      },
      { name: 'disabled', type: 'boolean', defaultValue: false },
      { name: 'rounded', type: 'boolean', defaultValue: false },
      { name: 'pill', type: 'boolean', defaultValue: false },
      { name: 'fullWidth', type: 'boolean', defaultValue: false },
      { name: 'noRipple', type: 'boolean', defaultValue: false },
      { name: 'elevation', type: 'number', defaultValue: 0 },
      { name: 'elevationHover', type: 'number', defaultValue: 0 },
      {
        name: 'type',
        type: 'select',
        options: ['button', 'submit', 'reset'],
        defaultValue: 'button',
      },
      { name: 'href', type: 'string', defaultValue: '' },
      { name: 'target', type: 'string', defaultValue: '_blank', label: 'Link Target' },
    ],
    events: [{ name: 'buttonClick', description: 'Emitted when the button is clicked.' }],
  },
  badge: {
    id: 'badge',
    tagName: 'ui-badge',
    label: 'Badge',
    description:
      'Status indicators and notification overlays with support for icons, animations, and gradients.',
    events: [
      {
        name: 'badgeClick',
        description: 'Emitted when the badge is clicked (requires interactive="true").',
      },
      {
        name: 'badgeClose',
        description: 'Emitted when the badge is dismissed (requires closeable="true").',
      },
    ],
    props: [
      { name: 'value', type: 'string', defaultValue: '5' },
      { name: 'icon', type: 'string', defaultValue: '' },
      {
        name: 'iconPosition',
        type: 'select',
        options: ['start', 'end'],
        defaultValue: 'start',
      },
      {
        name: 'color',
        type: 'select',
        options: ['primary', 'secondary', 'success', 'danger', 'warning', 'info'],
        defaultValue: 'danger',
      },
      {
        name: 'variant',
        type: 'select',
        options: ['standard', 'outlined', 'soft', 'bordered'],
        defaultValue: 'standard',
      },
      { name: 'size', type: 'select', options: ['sm', 'md', 'lg'], defaultValue: 'md' },
      {
        name: 'gradient',
        type: 'select',
        options: [
          '',
          'blue-purple',
          'green-teal',
          'orange-red',
          'pink-purple',
          'blue-green',
          'purple-pink',
          'cyan-blue',
          'yellow-orange',
          'indigo-purple',
        ],
        defaultValue: '',
      },
      {
        name: 'shape',
        type: 'select',
        options: ['default', 'circle', 'square'],
        defaultValue: 'default',
      },
      {
        name: 'position',
        type: 'select',
        options: ['top-right', 'top-left', 'bottom-right', 'bottom-left'],
        defaultValue: 'top-right',
      },
      {
        name: 'animation',
        type: 'select',
        options: ['none', 'pulse', 'bounce', 'shake'],
        defaultValue: 'none',
      },
      { name: 'dot', type: 'boolean', defaultValue: false },
      { name: 'glow', type: 'boolean', defaultValue: false },
      { name: 'interactive', type: 'boolean', defaultValue: false },
      { name: 'closeable', type: 'boolean', defaultValue: false },
    ],
  },
  card: {
    id: 'card',
    tagName: 'ui-card',
    label: 'Card',
    description:
      'A versatile container for content with support for headers, footers, cover images, and interactive flipping.',
    props: [
      {
        name: 'variant',
        type: 'select',
        options: ['default', 'elevated', 'outlined', 'filled'],
        defaultValue: 'default',
      },
      { name: 'width', type: 'string', defaultValue: '100%' },
      { name: 'height', type: 'string', defaultValue: 'auto' },
      { name: 'borderRadius', type: 'string', defaultValue: '12px' },
      { name: 'border', type: 'string', defaultValue: '1px solid rgba(128,128,128,0.2)' },
      { name: 'hoverable', type: 'boolean', defaultValue: false },
      { name: 'flippable', type: 'boolean', defaultValue: false },
      { name: 'showMenu', type: 'boolean', defaultValue: false },
      { name: 'menuItems', type: 'json', defaultValue: [] },
      { name: 'expandable', type: 'boolean', defaultValue: false },
      { name: 'loading', type: 'boolean', defaultValue: false },
      { name: 'selectable', type: 'boolean', defaultValue: false },
      { name: 'selected', type: 'boolean', defaultValue: false },
      { name: 'href', type: 'string', defaultValue: '' },
    ],
    events: [
      { name: 'menuItemClick', description: 'Emitted when a menu item is clicked.' },
      { name: 'cardSelect', description: 'Emitted when a selectable card is clicked.' },
    ],
    slots: [
      { name: 'header', content: '<h3>Card Title</h3>' },
      { name: 'content', content: '<p>Card body content goes here.</p>' },
      { name: 'footer', content: '<button>Action</button>' },
    ],
  },
  avatar: {
    id: 'avatar',
    tagName: 'ui-avatar',
    label: 'Avatar',
    description:
      'User profile representation with support for images, initials, icons, and status indicators.',
    props: [
      { name: 'name', type: 'string', defaultValue: 'John Doe' },
      { name: 'content', type: 'string', defaultValue: 'JD' },
      { name: 'src', type: 'string', defaultValue: 'https://i.pravatar.cc/150?img=1' },
      { name: 'icon', type: 'string', defaultValue: '' },
      { name: 'size', type: 'string', defaultValue: '40px' },
      {
        name: 'shape',
        type: 'select',
        options: ['circle', 'square', 'squircle', 'hexagon'],
        defaultValue: 'circle',
      },
      {
        name: 'status',
        type: 'select',
        options: ['none', 'online', 'offline', 'busy', 'away'],
        defaultValue: 'none',
      },
      { name: 'badge', type: 'string', defaultValue: '' },
      { name: 'bgColor', type: 'string', defaultValue: '' },
      { name: 'textColor', type: 'string', defaultValue: '' },
      { name: 'maxInitials', type: 'number', defaultValue: 2 },
      { name: 'clickable', type: 'boolean', defaultValue: false },
    ],
    events: [{ name: 'avatarClick', description: 'Emitted when the avatar is clicked.' }],
  },
  'avatar-group': {
    id: 'avatar-group',
    tagName: 'ui-avatar-group',
    label: 'Avatar Group',
    props: [
      { name: 'max', type: 'number', defaultValue: 5 },
      { name: 'size', type: 'string', defaultValue: '40px' },
      {
        name: 'layout',
        type: 'select',
        options: ['stack', 'grid'],
        defaultValue: 'stack',
      },
      {
        name: 'avatars',
        type: 'json',
        defaultValue: JSON.stringify([
          { src: 'https://i.pravatar.cc/150?img=1', name: 'User 1' },
          { src: 'https://i.pravatar.cc/150?img=2', name: 'User 2' },
          { src: 'https://i.pravatar.cc/150?img=3', name: 'User 3' },
          { content: 'AB', name: 'User 4' },
          { content: 'CD', name: 'User 5' },
        ]),
      },
    ],
  },
  skeleton: {
    id: 'skeleton',
    tagName: 'skeleton-loader',
    label: 'Skeleton',
    description: 'A loading placeholder for content that is still fetching.',
    props: [
      {
        name: 'shape',
        type: 'select',
        options: [
          'rectangle',
          'circle',
          'square',
          'oval',
          'rounded-square',
          'rounded-rectangle',
          'image',
        ],
        defaultValue: 'rectangle',
      },
      { name: 'width', type: 'string', defaultValue: '200px' },
      { name: 'height', type: 'string', defaultValue: '20px' },
      { name: 'borderRadius', type: 'string', defaultValue: '4px' },
      { name: 'animationType', type: 'select', options: ['pulse', 'wave'], defaultValue: 'pulse' },
      { name: 'animated', type: 'boolean', defaultValue: true },
      { name: 'size', type: 'select', options: ['sm', 'md', 'lg'], defaultValue: 'md' },
    ],
  },
  rating: {
    id: 'rating',
    tagName: 'ui-rating',
    label: 'Rating',
    description: 'An interactive component for collecting user feedback via symbols.',
    events: [{ name: 'ratingChange', description: 'Emitted when the rating value is updated.' }],
    props: [
      { name: 'type', type: 'select', options: ['star', 'smiley', 'thumb'], defaultValue: 'star' },
      { name: 'value', type: 'number', defaultValue: 3 },
      { name: 'max', type: 'number', defaultValue: 5 },
      { name: 'allowHalf', type: 'boolean', defaultValue: false },
      { name: 'showValue', type: 'boolean', defaultValue: false },
      { name: 'readonly', type: 'boolean', defaultValue: false },
      { name: 'disabled', type: 'boolean', defaultValue: false },
      { name: 'size', type: 'select', options: ['sm', 'md', 'lg'], defaultValue: 'md' },
      {
        name: 'color',
        type: 'select',
        options: ['primary', 'warning', 'success', 'danger'],
        defaultValue: 'warning',
      },
    ],
  },
  pill: {
    id: 'pill',
    tagName: 'ui-pill',
    label: 'Pill',
    description: 'Compact interactive labels for categorization, selection, or status indicators.',
    events: [
      { name: 'pillClick', description: 'Emitted when the pill is clicked.' },
      { name: 'pillRemove', description: 'Emitted when the remove icon is clicked.' },
      { name: 'pillSelect', description: 'Emitted when selection state changes.' },
    ],
    props: [
      { name: 'label', type: 'string', defaultValue: 'Tag Label' },
      {
        name: 'color',
        type: 'select',
        options: ['primary', 'secondary', 'success', 'danger', 'warning', 'info', 'default'],
        defaultValue: 'primary',
      },
      {
        name: 'variant',
        type: 'select',
        options: ['filled', 'outlined', 'soft', 'gradient', 'bordered'],
        defaultValue: 'filled',
      },
      { name: 'size', type: 'select', options: ['sm', 'md', 'lg'], defaultValue: 'md' },
      {
        name: 'orientation',
        type: 'select',
        options: ['horizontal', 'vertical', 'vertical-text', 'vertical-rotated'],
        defaultValue: 'horizontal',
      },
      { name: 'icon', type: 'string', defaultValue: '' },
      { name: 'iconPosition', type: 'select', options: ['start', 'end'], defaultValue: 'start' },
      { name: 'avatar', type: 'string', defaultValue: '' },
      { name: 'counter', type: 'string', defaultValue: '' },
      { name: 'gradient', type: 'string', defaultValue: '' },
      { name: 'selected', type: 'boolean', defaultValue: false },
      { name: 'clickable', type: 'boolean', defaultValue: false },
      { name: 'removable', type: 'boolean', defaultValue: false },
      { name: 'loading', type: 'boolean', defaultValue: false },
      { name: 'disabled', type: 'boolean', defaultValue: false },
      { name: 'tooltip', type: 'string', defaultValue: '' },
      { name: 'closeIcon', type: 'string', defaultValue: '✕' },
      {
        name: 'animation',
        type: 'select',
        options: ['fade', 'scale', 'slide', 'none'],
        defaultValue: 'scale',
      },
    ],
  },
  switch: {
    id: 'switch',
    tagName: 'ui-switch',
    label: 'Switch',
    description:
      'Binary toggle with support for multiple shapes, sizes, and custom icon indicators.',
    props: [
      { name: 'checked', type: 'boolean', defaultValue: false },
      { name: 'label', type: 'string', defaultValue: 'Label' },
      {
        name: 'size',
        type: 'select',
        options: ['xs', 'sm', 'md', 'lg', 'xl'],
        defaultValue: 'md',
      },
      {
        name: 'variant',
        type: 'select',
        options: ['primary', 'secondary', 'success', 'danger', 'warning', 'info'],
        defaultValue: 'primary',
      },
      {
        name: 'shape',
        type: 'select',
        options: ['default', 'rounded', 'pill', 'square'],
        defaultValue: 'default',
      },
      {
        name: 'labelPosition',
        type: 'select',
        options: ['left', 'right'],
        defaultValue: 'right',
      },
      { name: 'iconOn', type: 'string', defaultValue: '' },
      { name: 'iconOff', type: 'string', defaultValue: '' },
      { name: 'showDefaultIcons', type: 'boolean', defaultValue: false },
      { name: 'disabled', type: 'boolean', defaultValue: false },
      { name: 'loading', type: 'boolean', defaultValue: false },
      { name: 'required', type: 'boolean', defaultValue: false },
    ],
    events: [{ name: 'switchChange', description: 'Emitted when checked state changes.' }],
  },
  accordion: {
    id: 'accordion',
    tagName: 'ui-accordion',
    label: 'Accordion',
    events: [
      { name: 'accordionChange', description: 'Emitted when the selected panel(s) change.' },
    ],
    props: [
      {
        name: 'variant',
        type: 'select',
        options: ['default', 'bordered', 'splitted', 'light', 'shadow'],
        defaultValue: 'default',
        description: 'The visual style of the accordion.',
      },
      {
        name: 'size',
        type: 'select',
        options: ['sm', 'md', 'lg'],
        defaultValue: 'md',
        description: 'The size of the accordion items.',
      },
      {
        name: 'multiple',
        type: 'boolean',
        defaultValue: false,
        description: 'Allow multiple items to be expanded at once.',
      },
      {
        name: 'dense',
        type: 'boolean',
        defaultValue: false,
        description: 'Reduce spacing for a more compact layout.',
      },
      {
        name: 'disabled',
        type: 'boolean',
        defaultValue: false,
        description: 'Disable the entire accordion interaction.',
      },
      {
        name: 'loading',
        type: 'boolean',
        defaultValue: false,
        description: 'Show a loading state/skeleton.',
      },
      {
        name: 'rtl',
        type: 'boolean',
        defaultValue: false,
        description: 'Enable Right-to-Left layout support.',
      },
      {
        name: 'lazy',
        type: 'boolean',
        defaultValue: false,
        description: 'Lazy load content when expanded.',
      },
      {
        name: 'enableSearch',
        type: 'boolean',
        defaultValue: false,
        description: 'Show a search bar filtering items.',
      },
      {
        name: 'searchPlaceholder',
        type: 'string',
        defaultValue: 'Search...',
        description: 'Placeholder text for the search input.',
      },
      {
        name: 'enableExpandCollapseAll',
        type: 'boolean',
        defaultValue: false,
        description: 'Show controls to expand/collapse all items (Requires multiple="true").',
      },
      {
        name: 'enableDragDrop',
        type: 'boolean',
        defaultValue: false,
        description: 'Allow reordering items via drag and drop.',
      },
      {
        name: 'enablePersistence',
        type: 'boolean',
        defaultValue: false,
        description: 'Persist expanded state to local storage.',
      },
      {
        name: 'enableNested',
        type: 'boolean',
        defaultValue: false,
        description: 'Support nested accordions.',
      },
      {
        name: 'showNumbers',
        type: 'boolean',
        defaultValue: false,
        description: 'Show index numbers next to items.',
      },
      {
        name: 'iconPosition',
        type: 'select',
        options: ['start', 'end'],
        defaultValue: 'end',
        description: 'Position of the expand/collapse icon.',
      },
      {
        name: 'hideArrow',
        type: 'boolean',
        defaultValue: false,
        description: 'Hide the expand/collapse arrow icon.',
      },
      {
        name: 'arrowIconExpanded',
        type: 'string',
        defaultValue: '▼',
        label: 'Expanded Icon',
        description: 'Icon to show when item is open (defaults to ▼).',
      },
      {
        name: 'arrowIconCollapsed',
        type: 'string',
        defaultValue: '▶',
        label: 'Collapsed Icon',
        description: 'Icon to show when item is closed (defaults to ▶).',
      },
      {
        name: 'selectedHeaderColor',
        type: 'string',
        defaultValue: '#3b82f6',
        label: 'Selected Color',
        description: 'Color of the header for the open item.',
      },
      {
        name: 'animationDuration',
        type: 'number',
        defaultValue: 300,
        description: 'Duration of expand/collapse animation (ms).',
      },
      {
        name: 'headerLevel',
        type: 'number',
        defaultValue: 3,
        description: 'HTML heading level for accessibility (h1-h6).',
      },
      {
        name: 'items',
        type: 'json',
        defaultValue: JSON.stringify([
          { id: '1', title: 'Item 1', content: 'Content 1' },
          { id: '2', title: 'Item 2', content: 'Content 2' },
          { id: '3', title: 'Item 3', content: 'Content 3' },
        ]),
        description: 'JSON array of accordion items.',
      },
      {
        name: 'defaultOpen',
        type: 'string',
        defaultValue: '',
        label: 'Default Open IDs',
        description: 'Comma-separated IDs of items open by default.',
      },
    ],
  },

  dropdown: {
    id: 'dropdown',
    tagName: 'ui-dropdown',
    label: 'Dropdown',
    description:
      'A versatile dropdown component supporting single/multi-selection, cascading nodes, and searching.',
    events: [{ name: 'valueChange', description: 'Emitted when the selected value(s) change.' }],
    props: [
      { name: 'placeholder', type: 'string', defaultValue: 'Select an option' },
      { name: 'multiSelect', type: 'boolean', defaultValue: false },
      { name: 'cascading', type: 'boolean', defaultValue: false },
      { name: 'searchable', type: 'boolean', defaultValue: false },
      { name: 'clearable', type: 'boolean', defaultValue: true },
      { name: 'disabled', type: 'boolean', defaultValue: false },
      { name: 'size', type: 'select', options: ['sm', 'md', 'lg'], defaultValue: 'md' },
      { name: 'maxHeight', type: 'number', defaultValue: 300 },
      {
        name: 'options',
        type: 'json',
        defaultValue: JSON.stringify([
          { label: 'Option 1', value: '1', icon: '⭐' },
          { label: 'Option 2', value: '2', icon: '🎯' },
          { label: 'Option 3', value: '3', icon: '🚀' },
        ]),
      },
    ],
  },
  tabs: {
    id: 'tabs',
    tagName: 'ui-tabs',
    label: 'Tabs',
    description: 'A structural component for organizing content into separate views.',
    events: [
      { name: 'tabChange', description: 'Emitted when the active tab changes.' },
      { name: 'tabClose', description: 'Emitted when a tab is closed.' },
      { name: 'closeAll', description: 'Emitted when all tabs are closed.' },
    ],
    props: [
      {
        name: 'orientation',
        type: 'select',
        options: ['horizontal', 'vertical'],
        defaultValue: 'horizontal',
      },
      {
        name: 'variant',
        type: 'select',
        options: ['line', 'card', 'pill', 'subtle', 'glass'],
        defaultValue: 'line',
      },
      { name: 'size', type: 'select', options: ['sm', 'md', 'lg'], defaultValue: 'md' },
      {
        name: 'scrollMode',
        type: 'select',
        options: ['auto', 'manual', 'none'],
        defaultValue: 'auto',
      },
      {
        name: 'scrollButtonPlacement',
        type: 'select',
        options: ['split', 'start', 'end'],
        defaultValue: 'split',
      },
      { name: 'showTabList', type: 'boolean', defaultValue: false },
      { name: 'showCloseAll', type: 'boolean', defaultValue: false },
      {
        name: 'selectionAnimation',
        type: 'select',
        options: ['slide', 'fade', 'none'],
        defaultValue: 'slide',
      },
      {
        name: 'items',
        type: 'json',
        defaultValue: JSON.stringify([
          {
            id: 'tab1',
            title: 'Home',
            icon: '🏠',
            content: '<div style="padding: 20px;">Home Content</div>',
          },
          {
            id: 'tab2',
            title: 'Profile',
            icon: '👤',
            content: '<div style="padding: 20px;">Profile Content</div>',
          },
          {
            id: 'tab3',
            title: 'Settings',
            icon: '⚙️',
            content: '<div style="padding: 20px;">Settings Content</div>',
            closable: true,
          },
        ]),
      },
    ],
  },
  dialog: {
    id: 'dialog',
    tagName: 'dialog-box',
    label: 'Dialog',
    description: 'A modal window for focusing user attention on specific tasks or information.',
    events: [
      { name: 'dialogOpened', description: 'Emitted when the dialog opens.' },
      { name: 'dialogClosed', description: 'Emitted when the dialog closes.' },
      { name: 'ok', description: 'Emitted when the OK button is clicked.' },
      { name: 'cancel', description: 'Emitted when the Cancel button is clicked.' },
    ],
    allowTrigger: true,
    triggerLabel: 'Open Dialog',
    props: [
      { name: 'dialogTitle', type: 'string', defaultValue: 'Dialog Title' },
      {
        name: 'size',
        type: 'select',
        options: ['xs', 'sm', 'md', 'lg', 'xl', 'fill'],
        defaultValue: 'md',
      },
      {
        name: 'variant',
        type: 'select',
        options: ['outlined', 'filled'],
        defaultValue: 'outlined',
      },
      {
        name: 'status',
        type: 'select',
        options: ['default', 'info', 'success', 'warning', 'error'],
        defaultValue: 'default',
      },
      {
        name: 'backdrop',
        type: 'select',
        options: ['default', 'static', 'none'],
        defaultValue: 'default',
      },
      {
        name: 'position',
        type: 'select',
        options: ['center', 'top', 'bottom', 'left', 'right', 'top-right'],
        defaultValue: 'center',
      },
      { name: 'draggable', type: 'boolean', defaultValue: false },
      { name: 'resizable', type: 'boolean', defaultValue: false },
      { name: 'showHeader', type: 'boolean', defaultValue: true },
      { name: 'showFooter', type: 'boolean', defaultValue: true },
      { name: 'okText', type: 'string', defaultValue: 'OK' },
      { name: 'cancelText', type: 'string', defaultValue: 'Cancel' },
      { name: 'width', type: 'string', defaultValue: '500px' },
      { name: 'height', type: 'string', defaultValue: '' },
      { name: 'backdropBlur', type: 'string', defaultValue: '4px' },
    ],
    slots: [
      { name: '', content: '<p>This is the main content area of the dialog.</p>' },
      { name: 'footer', content: '<button>Custom Footer Action</button>' },
    ],
  },
  chip: {
    id: 'chip',
    tagName: 'ui-chip',
    label: 'Chip',
    description: 'Interactive tags with support for icons, avatars, and animations.',
    events: [
      { name: 'chipClick', description: 'Emitted when the chip is clicked.' },
      { name: 'chipRemove', description: 'Emitted when the remove icon is clicked.' },
    ],
    props: [
      { name: 'label', type: 'string', defaultValue: 'Premium Chip' },
      {
        name: 'color',
        type: 'select',
        options: ['default', 'primary', 'secondary', 'success', 'danger', 'warning', 'info'],
        defaultValue: 'default',
      },
      {
        name: 'variant',
        type: 'select',
        options: ['default', 'flat', 'outlined', 'glass'],
        defaultValue: 'default',
      },
      { name: 'size', type: 'select', options: ['sm', 'md', 'lg'], defaultValue: 'md' },
      { name: 'icon', type: 'string', defaultValue: '🏷️' },
      { name: 'image', type: 'string', defaultValue: '' },
      { name: 'userAvatar', type: 'string', defaultValue: '' },
      { name: 'removable', type: 'boolean', defaultValue: false },
      { name: 'clickable', type: 'boolean', defaultValue: false },
      { name: 'disabled', type: 'boolean', defaultValue: false },
      {
        name: 'animation',
        type: 'select',
        options: ['scale', 'fade', 'slide', 'bounce', 'none'],
        defaultValue: 'scale',
      },
    ],
  },
  breadcrumb: {
    id: 'breadcrumb',
    tagName: 'ui-breadcrumb',
    label: 'Breadcrumb',
    description: 'A navigation aid for tracking location within an application hierarchy.',
    props: [
      {
        name: 'items',
        type: 'json',
        defaultValue: JSON.stringify([
          { label: 'Home', icon: '🏠', href: '/' },
          { label: 'Products', href: '/products', badge: 'New', badgeVariant: 'success' },
          { label: 'Electronics', active: true },
        ]),
      },
      { name: 'separator', type: 'string', defaultValue: '/' },
      { name: 'size', type: 'select', options: ['sm', 'md', 'lg'], defaultValue: 'md' },
      {
        name: 'variant',
        type: 'select',
        options: ['default', 'pills', 'glass'],
        defaultValue: 'default',
      },
      { name: 'maxItems', type: 'number', defaultValue: 0 },
      { name: 'showHome', type: 'boolean', defaultValue: false },
      { name: 'homeIcon', type: 'string', defaultValue: '🏠' },
    ],
    events: [
      { name: 'breadcrumbClick', description: 'Emitted when a breadcrumb item is clicked.' },
    ],
  },
  'range-slider': {
    id: 'range-slider',
    tagName: 'ui-range-slider',
    label: 'Range Slider',
    props: [
      { name: 'min', type: 'number', defaultValue: 0 },
      { name: 'max', type: 'number', defaultValue: 100 },
      { name: 'value', type: 'number', defaultValue: 50 },
      { name: 'step', type: 'number', defaultValue: 1 },
    ],
  },
  'advanced-data-table': {
    id: 'advanced-data-table',
    tagName: 'ui-data-table',
    label: 'Advanced Data Table',
    description:
      "Our Data Table isn't just a list. It's a full-featured management system with virtualization, inline editing, selection, and complex filtering.",
    features: [
      'Handle 100,000+ rows with ease',
      'Multi-column sorting & pinning',
      'Customizable cell templates',
      'Virtual Scrolling',
      'Inline Editing',
      'Advanced Filtering',
    ],
    props: [
      { name: 'rows', type: 'json', defaultValue: JSON.stringify([]) },
      { name: 'columns', type: 'json', defaultValue: JSON.stringify([]) },
      { name: 'virtual-scroll', type: 'boolean', defaultValue: true },
      { name: 'sortable', type: 'boolean', defaultValue: true },
    ],
  },
  'bar-chart': {
    id: 'bar-chart',
    tagName: 'ui-bar-chart',
    label: 'Bar Chart',
    description:
      'Bring your data to life with our high-performance charting suite. Built for real-time updates and interactive exploration.',
    features: [
      'Responsive & interactive Charts',
      'Customizable tooltips & legends',
      'Smooth transition animations',
      'Real-time data updates',
      'Dark mode support',
    ],
    props: [
      { name: 'data', type: 'json', defaultValue: JSON.stringify([12, 19, 3, 5, 2, 3]) },
      {
        name: 'labels',
        type: 'json',
        defaultValue: JSON.stringify(['Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange']),
      },
      { name: 'responsive', type: 'boolean', defaultValue: true },
    ],
  },
  aside: {
    id: 'aside',
    tagName: 'aside-panel',
    label: 'Aside Panel',
    description:
      'A versatile slide-out panel for navigation, details, or settings with support for multiple directions and premium effects.',
    events: [
      { name: 'asideOpened', description: 'Emitted when the panel opens.' },
      { name: 'asideClosed', description: 'Emitted when the panel closes.' },
      { name: 'asideResized', description: 'Emitted when the panel is resized.' },
    ],
    allowTrigger: true,
    triggerLabel: 'Open Aside Panel',
    props: [
      {
        name: 'open',
        type: 'boolean',
        defaultValue: false,
        description: 'Whether the panel is visible.',
      },
      {
        name: 'direction',
        type: 'select',
        options: ['left', 'right', 'top', 'bottom'],
        defaultValue: 'right',
        description: 'Direction from which the panel slides in.',
      },
      {
        name: 'size',
        type: 'string',
        defaultValue: '400px',
        description: 'Width or height of the panel.',
      },
      {
        name: 'variant',
        type: 'select',
        options: ['default', 'glass'],
        defaultValue: 'default',
        description: 'Visual style variant of the panel.',
      },
      {
        name: 'backdropBlur',
        type: 'string',
        defaultValue: '0px',
        description: 'Backdrop blur intensity (e.g., 8px).',
      },
      {
        name: 'loading',
        type: 'boolean',
        defaultValue: false,
        description: 'Show a loading indicator overlay.',
      },
      {
        name: 'persistKey',
        type: 'string',
        defaultValue: '',
        description: 'Unique key to persist state in local storage.',
      },
      {
        name: 'resizable',
        type: 'boolean',
        defaultValue: false,
        description: 'Allow users to resize the panel.',
      },
      {
        name: 'minSize',
        type: 'number',
        defaultValue: 250,
        description: 'Minimum allowed size during resizing.',
      },
      {
        name: 'maxSize',
        type: 'number',
        defaultValue: 600,
        description: 'Maximum allowed size during resizing.',
      },
      {
        name: 'closeable',
        type: 'boolean',
        defaultValue: true,
        description: 'Whether to show a close button.',
      },
      {
        name: 'closeOnOverlayClick',
        type: 'boolean',
        defaultValue: true,
        description: 'Close when background is clicked.',
      },
      {
        name: 'closeOnEscape',
        type: 'boolean',
        defaultValue: true,
        description: 'Close when ESC key is pressed.',
      },
    ],
    slots: [
      { name: 'header', content: '<h3>Panel Header</h3>' },
      { name: 'content', content: '<p>Main content area for documentation and examples.</p>' },
      { name: 'footer', content: '<button>Action Button</button>' },
    ],
  },
  divider: {
    id: 'divider',
    tagName: 'ui-divider',
    label: 'Divider',
    description: 'A structural component for separating content with lines, text, or icons.',
    events: [
      {
        name: 'dividerClick',
        description: 'Emitted when the divider is clicked (requires clickable: true).',
      },
    ],
    props: [
      {
        name: 'text',
        type: 'string',
        defaultValue: '',
        description: 'Text to display on the divider.',
      },
      {
        name: 'icon',
        type: 'string',
        defaultValue: '',
        description: 'Icon to display (emoji or character).',
      },
      {
        name: 'orientation',
        type: 'select',
        options: ['horizontal', 'vertical'],
        defaultValue: 'horizontal',
        description: 'Orientation of the divider.',
      },
      {
        name: 'variant',
        type: 'select',
        options: ['solid', 'dashed', 'dotted', 'double-solid', 'gradient'],
        defaultValue: 'solid',
        description: 'Line style variant.',
      },
      {
        name: 'size',
        type: 'select',
        options: ['sm', 'md', 'lg'],
        defaultValue: 'md',
        description: 'Thickness preset.',
      },
      {
        name: 'color',
        type: 'select',
        options: ['primary', 'secondary', 'success', 'danger', 'warning', 'info'],
        defaultValue: '',
        description: 'Theme color.',
      },
      {
        name: 'textAlign',
        type: 'select',
        options: ['left', 'center', 'right'],
        defaultValue: 'center',
        description: 'Text alignment.',
      },
      {
        name: 'verticalAlign',
        type: 'select',
        options: ['top', 'center', 'bottom'],
        defaultValue: 'center',
        description: 'Vertical alignment (for vertical orientation).',
      },
      {
        name: 'thickness',
        type: 'string',
        defaultValue: '',
        description: 'Custom line thickness (e.g. "2px").',
      },
      { name: 'opacity', type: 'number', defaultValue: 1, description: 'Opacity (0 to 1).' },
      {
        name: 'loading',
        type: 'boolean',
        defaultValue: false,
        description: 'Show loading shimmer effect.',
      },
      {
        name: 'shadow',
        type: 'boolean',
        defaultValue: false,
        description: 'Enable shadow effect.',
      },
      { name: 'glow', type: 'boolean', defaultValue: false, description: 'Enable glow effect.' },
      {
        name: 'clickable',
        type: 'boolean',
        defaultValue: false,
        description: 'Make the divider interactive.',
      },
      {
        name: 'badge',
        type: 'string',
        defaultValue: '',
        description: 'Badge text to display next to text.',
      },
      {
        name: 'pattern',
        type: 'select',
        options: ['none', 'dots', 'stripes', 'wavy', 'zigzag'],
        defaultValue: 'none',
        description: 'Pattern style for the line.',
      },
      {
        name: 'shape',
        type: 'select',
        options: ['none', 'curve', 'tilt', 'triangle', 'wave', 'zigzag', 'arrow'],
        defaultValue: 'none',
        description: 'SVG shape divider type.',
      },
      {
        name: 'responsive',
        type: 'select',
        options: ['none', 'sm', 'md', 'lg'],
        defaultValue: 'none',
        description: 'Switch orientation at breakpoint.',
      },
      {
        name: 'inset',
        type: 'select',
        options: ['none', 'start', 'end', 'both'],
        defaultValue: 'none',
        description: 'Add margin at either end.',
      },
      {
        name: 'spacing',
        type: 'select',
        options: ['none', 'compact', 'comfortable', 'spacious'],
        defaultValue: 'none',
        description: 'Vertical margin preset.',
      },
    ],
    slots: [
      { name: 'start', content: '<span>⭐</span>' },
      { name: 'end', content: '<ui-badge value="New"></ui-badge>' },
    ],
  },
  tag: {
    id: 'tag',
    tagName: 'ui-tag',
    label: 'Tag',
    description: 'Versatile labels for categorization, status, and metadata.',
    events: [
      { name: 'tagClick', description: 'Emitted when the tag is clicked.' },
      { name: 'tagRemove', description: 'Emitted when the remove icon is clicked.' },
    ],
    props: [
      { name: 'label', type: 'string', defaultValue: 'Category Tag' },
      {
        name: 'color',
        type: 'select',
        options: ['default', 'primary', 'success', 'danger', 'warning', 'info', 'secondary'],
        defaultValue: 'primary',
      },
      {
        name: 'variant',
        type: 'select',
        options: ['filled', 'outlined', 'light', 'dot'],
        defaultValue: 'filled',
      },
      { name: 'size', type: 'select', options: ['sm', 'md', 'lg'], defaultValue: 'md' },
      { name: 'icon', type: 'string', defaultValue: '' },
      { name: 'iconPos', type: 'select', options: ['start', 'end'], defaultValue: 'start' },
      { name: 'badge', type: 'string', defaultValue: '' },
      { name: 'counter', type: 'string', defaultValue: '' },
      { name: 'rounded', type: 'boolean', defaultValue: false },
      { name: 'removable', type: 'boolean', defaultValue: false },
      { name: 'loading', type: 'boolean', defaultValue: false },
      { name: 'pulse', type: 'boolean', defaultValue: false },
      {
        name: 'elevation',
        type: 'select',
        options: ['0', '1', '2', '3'],
        defaultValue: '0',
      },
    ],
  },
  'tag-group': {
    id: 'tag-group',
    tagName: 'ui-tag-group',
    label: 'Tag Group',
    props: [
      { name: 'max', type: 'number', defaultValue: 0 },
      {
        name: 'selectionMode',
        type: 'select',
        options: ['none', 'single', 'multiple'],
        defaultValue: 'none',
      },
      { name: 'overlap', type: 'boolean', defaultValue: false },
      { name: 'spacing', type: 'string', defaultValue: '8px' },
      { name: 'collapsible', type: 'boolean', defaultValue: false },
      { name: 'creatable', type: 'boolean', defaultValue: false },
      { name: 'searchable', type: 'boolean', defaultValue: false },
    ],
  },
  'app-library': {
    id: 'app-library',
    tagName: 'app-library',
    label: 'App Library',
    description: 'A comprehensive gallery and directory of all available UI components.',
    props: [
      {
        name: 'mode',
        type: 'select',
        options: ['demo', 'doc'],
        defaultValue: 'demo',
      },
    ],
  },
  stepper: {
    id: 'stepper',
    tagName: 'ui-stepper',
    label: 'Stepper',
    description: 'A component for guiding users through a series of steps in a process.',
    events: [
      { name: 'stepChange', description: 'Emitted when the active step changes.' },
      { name: 'stepClick', description: 'Emitted when a step marker is clicked.' },
    ],
    props: [
      {
        name: 'orientation',
        type: 'select',
        options: ['horizontal', 'vertical'],
        defaultValue: 'horizontal',
      },
      {
        name: 'variant',
        type: 'select',
        options: ['default', 'navigation', 'panel', 'inline'],
        defaultValue: 'default',
      },
      { name: 'size', type: 'select', options: ['sm', 'md', 'lg'], defaultValue: 'md' },
      { name: 'activeStep', type: 'number', defaultValue: 0 },
      { name: 'progressDot', type: 'boolean', defaultValue: false },
      { name: 'showDescriptions', type: 'boolean', defaultValue: true },
      { name: 'showNumbers', type: 'boolean', defaultValue: true },
      {
        name: 'labelPlacement',
        type: 'select',
        options: ['horizontal', 'vertical'],
        defaultValue: 'horizontal',
      },
      {
        name: 'labelPosition',
        type: 'select',
        options: ['right', 'left', 'top', 'bottom'],
        defaultValue: 'right',
      },
      {
        name: 'steps',
        type: 'json',
        defaultValue: JSON.stringify([
          { id: '1', label: 'Step 1', description: 'Description 1', status: 'completed' },
          { id: '2', label: 'Step 2', description: 'Description 2', status: 'active', percent: 75 },
          { id: '3', label: 'Step 3', description: 'Description 3', status: 'pending' },
        ]),
      },
    ],
  },
  timeline: {
    id: 'timeline',
    tagName: 'ui-timeline',
    label: 'Timeline',
    description:
      'A structural component for displaying a sequence of events in chronological order.',
    events: [{ name: 'itemClick', description: 'Emitted when a timeline item is clicked.' }],
    props: [
      {
        name: 'mode',
        type: 'select',
        options: ['vertical', 'horizontal'],
        defaultValue: 'vertical',
      },
      {
        name: 'align',
        type: 'select',
        options: ['left', 'right', 'alternate', 'top', 'bottom'],
        defaultValue: 'left',
      },
      { name: 'variant', type: 'select', options: ['default', 'panel'], defaultValue: 'default' },
      { name: 'marker', type: 'select', options: ['dot', 'number', 'icon'], defaultValue: 'dot' },
      { name: 'clickable', type: 'boolean', defaultValue: false },
      { name: 'reverse', type: 'boolean', defaultValue: false },
      { name: 'pending', type: 'boolean', defaultValue: false },
      { name: 'searchable', type: 'boolean', defaultValue: false },
      { name: 'multiline', type: 'boolean', defaultValue: false },
      {
        name: 'events',
        type: 'json',
        defaultValue: JSON.stringify([
          {
            label: 'Kickoff',
            timestamp: '09:00 AM',
            description: 'Project start',
            status: 'success',
          },
          {
            label: 'Design',
            timestamp: '11:00 AM',
            description: 'Reviewing mockups',
            status: 'active',
          },
          { label: 'Deploy', timestamp: '02:00 PM', description: 'Go live', status: 'pending' },
        ]),
      },
    ],
  },
  stack: {
    id: 'stack',
    tagName: 'ui-stack',
    label: 'Stack',
    description:
      'A primitive layout component for stacking items horizontally or vertically with optional overflow and overlap.',
    props: [
      {
        name: 'direction',
        type: 'select',
        options: ['horizontal', 'vertical'],
        defaultValue: 'horizontal',
      },
      {
        name: 'wrap',
        type: 'select',
        options: ['nowrap', 'wrap', 'wrap-reverse'],
        defaultValue: 'nowrap',
      },
      {
        name: 'align',
        type: 'select',
        options: ['start', 'center', 'end', 'stretch'],
        defaultValue: 'center',
      },
      {
        name: 'justify',
        type: 'select',
        options: ['start', 'center', 'end', 'space-between'],
        defaultValue: 'start',
      },
      { name: 'spacing', type: 'string', defaultValue: '8px' },
      { name: 'showDividers', type: 'boolean', defaultValue: false },
      {
        name: 'dividerType',
        type: 'select',
        options: ['solid', 'dashed', 'dotted'],
        defaultValue: 'solid',
      },
      { name: 'max', type: 'number', defaultValue: 0, description: 'Max items to show (0 = all)' },
      { name: 'overlap', type: 'boolean', defaultValue: false },
    ],
  },
  splitter: {
    id: 'splitter',
    tagName: 'ui-splitter',
    label: 'Splitter',
    description:
      'A draggable divider for resizable layouts, supporting both horizontal and vertical orientations and nested grids.',
    props: [
      {
        name: 'orientation',
        type: 'select',
        options: ['horizontal', 'vertical'],
        defaultValue: 'horizontal',
      },
      { name: 'initialSplit', type: 'number', defaultValue: 50 },
      { name: 'minSize', type: 'number', defaultValue: 10 },
    ],
    slots: [
      { name: 'start', content: '<div style="padding: 20px;">Start Pane</div>' },
      { name: 'end', content: '<div style="padding: 20px;">End Pane</div>' },
    ],
  },
  panel: {
    id: 'panel',
    tagName: 'ui-panel',
    label: 'Panel',
    description:
      'Flexible container component with themes, animations, badges, and window-like features.',
    props: [
      { name: 'panelTitle', type: 'string', defaultValue: 'Panel Title' },
      { name: 'panelSubtitle', type: 'string', defaultValue: '' },
      {
        name: 'theme',
        type: 'select',
        options: ['default', 'primary', 'secondary', 'success', 'warning', 'danger', 'info'],
        defaultValue: 'default',
      },
      {
        name: 'variant',
        type: 'select',
        options: ['elevated', 'outlined', 'filled', 'flat'],
        defaultValue: 'elevated',
      },
      { name: 'width', type: 'string', defaultValue: '400px' },
      { name: 'height', type: 'string', defaultValue: '300px' },
      {
        name: 'position',
        type: 'select',
        options: [
          'center',
          'top',
          'bottom',
          'left',
          'right',
          'top-right',
          'top-left',
          'bottom-right',
          'bottom-left',
        ],
        defaultValue: 'center',
      },
      { name: 'isDraggable', type: 'boolean', defaultValue: false },
      { name: 'resizable', type: 'boolean', defaultValue: false },
      { name: 'minimizable', type: 'boolean', defaultValue: false },
      { name: 'maximizable', type: 'boolean', defaultValue: false },
      { name: 'toggleable', type: 'boolean', defaultValue: false },
      { name: 'modal', type: 'boolean', defaultValue: false },
      { name: 'glass', type: 'boolean', defaultValue: false },
      { name: 'pinned', type: 'boolean', defaultValue: false },
      { name: 'loading', type: 'boolean', defaultValue: false },
      { name: 'persistKey', type: 'string', defaultValue: '' },
      { name: 'badge', type: 'string', defaultValue: '' },
      {
        name: 'badgeVariant',
        type: 'select',
        options: ['dot', 'count', 'text'],
        defaultValue: 'dot',
      },
      { name: 'closeable', type: 'boolean', defaultValue: true },
    ],
    events: [
      { name: 'panelClose', description: 'Emitted when the panel is closed.' },
      { name: 'panelMinimize', description: 'Emitted when the panel is minimized.' },
      { name: 'panelMaximize', description: 'Emitted when the panel is maximized.' },
    ],
  },
};
