import * as i0 from "@angular/core";
import * as i1 from "./generated/proxies";
import * as i2 from "./generated/boolean-value-accessor";
import * as i3 from "./generated/number-value-accessor";
import * as i4 from "./generated/radio-value-accessor";
import * as i5 from "./generated/select-value-accessor";
import * as i6 from "./generated/text-value-accessor";
export declare class QuartzModule {
    static ɵfac: i0.ɵɵFactoryDeclaration<QuartzModule, never>;
    static ɵmod: i0.ɵɵNgModuleDeclaration<QuartzModule, never, [typeof i1.QdsBadgeCounter, typeof i1.QdsBadgeIndicator, typeof i1.QdsBreadcrumbItem, typeof i1.QdsButton, typeof i1.QdsCheckbox, typeof i1.QdsChip, typeof i1.QdsDialog, typeof i1.QdsDivider, typeof i1.QdsDropdown, typeof i1.QdsFormMessage, typeof i1.QdsIcon, typeof i1.QdsInlineLink, typeof i1.QdsInput, typeof i1.QdsLabel, typeof i1.QdsListItem, typeof i1.QdsLoader, typeof i1.QdsNavListItem, typeof i1.QdsProgressBar, typeof i1.QdsRadio, typeof i1.QdsSelect, typeof i1.QdsStandaloneLink, typeof i1.QdsSwitch, typeof i1.QdsTab, typeof i1.QdsTabbar, typeof i1.QdsTable, typeof i1.QdsTableBody, typeof i1.QdsTableCell, typeof i1.QdsTableHead, typeof i1.QdsTableHeadCell, typeof i1.QdsTableRow, typeof i1.QdsTag, typeof i1.QdsTextarea, typeof i1.QdsTitle, typeof i1.QdsTooltip, typeof i2.BooleanValueAccessor, typeof i3.NumericValueAccessor, typeof i4.RadioValueAccessor, typeof i5.SelectValueAccessor, typeof i6.TextValueAccessor], [typeof i1.QdsBadgeCounter, typeof i1.QdsBadgeIndicator, typeof i1.QdsBreadcrumbItem, typeof i1.QdsButton, typeof i1.QdsCheckbox, typeof i1.QdsChip, typeof i1.QdsDialog, typeof i1.QdsDivider, typeof i1.QdsDropdown, typeof i1.QdsFormMessage, typeof i1.QdsIcon, typeof i1.QdsInlineLink, typeof i1.QdsInput, typeof i1.QdsLabel, typeof i1.QdsListItem, typeof i1.QdsLoader, typeof i1.QdsNavListItem, typeof i1.QdsProgressBar, typeof i1.QdsRadio, typeof i1.QdsSelect, typeof i1.QdsStandaloneLink, typeof i1.QdsSwitch, typeof i1.QdsTab, typeof i1.QdsTabbar, typeof i1.QdsTable, typeof i1.QdsTableBody, typeof i1.QdsTableCell, typeof i1.QdsTableHead, typeof i1.QdsTableHeadCell, typeof i1.QdsTableRow, typeof i1.QdsTag, typeof i1.QdsTextarea, typeof i1.QdsTitle, typeof i1.QdsTooltip, typeof i2.BooleanValueAccessor, typeof i3.NumericValueAccessor, typeof i4.RadioValueAccessor, typeof i5.SelectValueAccessor, typeof i6.TextValueAccessor]>;
    static ɵinj: i0.ɵɵInjectorDeclaration<QuartzModule>;
}
//# sourceMappingURL=quartz.module.d.ts.map